
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 21 23:57:08 PDT 2010
//----------------------------------------------------

package scomp;

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Mon Jun 21 23:57:08 PDT 2010
  */
public class DecafParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public DecafParser() {super();}

  /** Constructor which sets the default scanner. */
  public DecafParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\003\006\000\002\002\004\000\002\003" +
    "\007\000\002\003\007\000\002\003\010\000\002\004\004" +
    "\000\002\004\003\000\002\005\005\000\002\006\005\000" +
    "\002\006\003\000\002\007\003\000\002\007\006\000\002" +
    "\010\004\000\002\010\003\000\002\011\007\000\002\011" +
    "\007\000\002\011\010\000\002\011\010\000\002\012\003" +
    "\000\002\012\005\000\002\013\004\000\002\020\004\000" +
    "\002\020\005\000\002\020\005\000\002\020\006\000\002" +
    "\014\005\000\002\015\003\000\002\015\005\000\002\021" +
    "\003\000\002\021\003\000\002\016\003\000\002\016\004" +
    "\000\002\017\006\000\002\017\004\000\002\017\007\000" +
    "\002\017\011\000\002\017\007\000\002\017\004\000\002" +
    "\017\005\000\002\017\004\000\002\017\004\000\002\017" +
    "\003\000\002\022\005\000\002\022\006\000\002\022\006" +
    "\000\002\022\010\000\002\026\003\000\002\026\005\000" +
    "\002\027\003\000\002\027\003\000\002\023\003\000\002" +
    "\023\006\000\002\024\003\000\002\024\005\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\004" +
    "\000\002\025\004\000\002\025\005\000\002\030\003\000" +
    "\002\030\003\000\002\030\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\004\007\005\001\002\000\004\002\204\001" +
    "\002\000\004\054\006\001\002\000\004\021\007\001\002" +
    "\000\012\004\012\013\011\015\013\022\015\001\002\000" +
    "\004\054\173\001\002\000\004\054\uffe5\001\002\000\004" +
    "\054\uffe4\001\002\000\004\054\163\001\002\000\012\004" +
    "\012\013\011\015\013\022\160\001\002\000\004\002\001" +
    "\001\002\000\012\004\ufff4\013\ufff4\015\ufff4\022\ufff4\001" +
    "\002\000\012\004\ufffb\013\ufffb\015\ufffb\022\ufffb\001\002" +
    "\000\012\004\012\013\011\015\013\022\022\001\002\000" +
    "\004\054\024\001\002\000\004\002\ufffe\001\002\000\012" +
    "\004\ufff5\013\ufff5\015\ufff5\022\ufff5\001\002\000\004\017" +
    "\025\001\002\000\010\004\012\013\011\020\027\001\002" +
    "\000\004\054\156\001\002\000\004\021\035\001\002\000" +
    "\006\020\uffef\025\uffef\001\002\000\006\020\033\025\032" +
    "\001\002\000\006\004\012\013\011\001\002\000\004\021" +
    "\035\001\002\000\012\004\ufff1\013\ufff1\015\ufff1\022\ufff1" +
    "\001\002\000\030\004\012\005\050\006\036\010\040\012" +
    "\046\013\011\014\044\016\042\021\035\022\054\054\045" +
    "\001\002\000\004\017\141\001\002\000\004\044\136\001" +
    "\002\000\004\026\135\001\002\000\024\005\050\006\036" +
    "\010\040\012\046\014\044\016\042\021\035\022\133\054" +
    "\045\001\002\000\004\017\126\001\002\000\024\005\050" +
    "\006\036\010\040\012\046\014\044\016\042\021\035\022" +
    "\125\054\045\001\002\000\024\006\036\017\071\026\121" +
    "\027\075\031\065\050\072\051\067\052\076\054\045\001" +
    "\002\000\020\017\107\020\uffcf\023\110\024\uffcf\025\uffcf" +
    "\026\uffcf\044\uffcf\001\002\000\004\017\064\001\002\000" +
    "\004\054\060\001\002\000\004\026\056\001\002\000\024" +
    "\005\uffd8\006\uffd8\010\uffd8\012\uffd8\014\uffd8\016\uffd8\021" +
    "\uffd8\022\uffd8\054\uffd8\001\002\000\004\026\055\001\002" +
    "\000\024\005\uffe3\006\uffe3\010\uffe3\012\uffe3\014\uffe3\016" +
    "\uffe3\021\uffe3\022\uffe3\054\uffe3\001\002\000\034\004\uffec" +
    "\005\uffec\006\uffec\010\uffec\011\uffec\012\uffec\013\uffec\014" +
    "\uffec\015\uffec\016\uffec\021\uffec\022\uffec\054\uffec\001\002" +
    "\000\024\005\uffe0\006\uffe0\010\uffe0\012\uffe0\014\uffe0\016" +
    "\uffe0\021\uffe0\022\uffe0\054\uffe0\001\002\000\024\005\uffda" +
    "\006\uffda\010\uffda\012\uffda\014\uffda\016\uffda\021\uffda\022" +
    "\uffda\054\uffda\001\002\000\006\025\061\026\062\001\002" +
    "\000\006\025\uffe7\026\uffe7\001\002\000\004\054\063\001" +
    "\002\000\024\005\uffe8\006\uffe8\010\uffe8\012\uffe8\014\uffe8" +
    "\016\uffe8\021\uffe8\022\uffe8\054\uffe8\001\002\000\006\025" +
    "\uffe6\026\uffe6\001\002\000\022\006\036\017\071\027\075" +
    "\031\065\050\072\051\067\052\076\054\045\001\002\000" +
    "\022\006\036\017\071\027\075\031\065\050\072\051\067" +
    "\052\076\054\045\001\002\000\004\020\102\001\002\000" +
    "\012\020\uffc4\024\uffc4\025\uffc4\026\uffc4\001\002\000\012" +
    "\020\uffc9\024\uffc9\025\uffc9\026\uffc9\001\002\000\022\006" +
    "\036\017\071\027\075\031\065\050\072\051\067\052\076" +
    "\054\045\001\002\000\012\020\uffc5\024\uffc5\025\uffc5\026" +
    "\uffc5\001\002\000\012\020\uffcb\024\uffcb\025\uffcb\026\uffcb" +
    "\001\002\000\012\020\uffca\024\uffca\025\uffca\026\uffca\001" +
    "\002\000\022\006\036\017\071\027\075\031\065\050\072" +
    "\051\067\052\076\054\045\001\002\000\012\020\uffc3\024" +
    "\uffc3\025\uffc3\026\uffc3\001\002\000\012\020\uffc7\024\uffc7" +
    "\025\uffc7\026\uffc7\001\002\000\004\020\101\001\002\000" +
    "\012\020\uffc6\024\uffc6\025\uffc6\026\uffc6\001\002\000\004" +
    "\021\035\001\002\000\026\005\uffdf\006\uffdf\010\uffdf\011" +
    "\104\012\uffdf\014\uffdf\016\uffdf\021\uffdf\022\uffdf\054\uffdf" +
    "\001\002\000\004\021\035\001\002\000\024\005\uffde\006" +
    "\uffde\010\uffde\012\uffde\014\uffde\016\uffde\021\uffde\022\uffde" +
    "\054\uffde\001\002\000\012\020\uffc8\024\uffc8\025\uffc8\026" +
    "\uffc8\001\002\000\024\006\036\017\071\020\113\027\075" +
    "\031\065\050\072\051\067\052\076\054\045\001\002\000" +
    "\022\006\036\017\071\027\075\031\065\050\072\051\067" +
    "\052\076\054\045\001\002\000\004\024\112\001\002\000" +
    "\014\020\uffce\024\uffce\025\uffce\026\uffce\044\uffce\001\002" +
    "\000\012\020\uffd7\024\uffd7\025\uffd7\026\uffd7\001\002\000" +
    "\006\020\uffcd\025\uffcd\001\002\000\006\020\117\025\116" +
    "\001\002\000\022\006\036\017\071\027\075\031\065\050" +
    "\072\051\067\052\076\054\045\001\002\000\012\020\uffd6" +
    "\024\uffd6\025\uffd6\026\uffd6\001\002\000\006\020\uffcc\025" +
    "\uffcc\001\002\000\024\005\uffdc\006\uffdc\010\uffdc\012\uffdc" +
    "\014\uffdc\016\uffdc\021\uffdc\022\uffdc\054\uffdc\001\002\000" +
    "\004\026\123\001\002\000\024\005\uffdb\006\uffdb\010\uffdb" +
    "\012\uffdb\014\uffdb\016\uffdb\021\uffdb\022\uffdb\054\uffdb\001" +
    "\002\000\024\005\uffe2\006\uffe2\010\uffe2\012\uffe2\014\uffe2" +
    "\016\uffe2\021\uffe2\022\uffe2\054\uffe2\001\002\000\034\004" +
    "\uffea\005\uffea\006\uffea\010\uffea\011\uffea\012\uffea\013\uffea" +
    "\014\uffea\015\uffea\016\uffea\021\uffea\022\uffea\054\uffea\001" +
    "\002\000\022\006\036\017\071\027\075\031\065\050\072" +
    "\051\067\052\076\054\045\001\002\000\004\020\130\001" +
    "\002\000\004\021\035\001\002\000\024\005\uffdd\006\uffdd" +
    "\010\uffdd\012\uffdd\014\uffdd\016\uffdd\021\uffdd\022\uffdd\054" +
    "\uffdd\001\002\000\024\005\050\006\036\010\040\012\046" +
    "\014\044\016\042\021\035\022\134\054\045\001\002\000" +
    "\034\004\uffeb\005\uffeb\006\uffeb\010\uffeb\011\uffeb\012\uffeb" +
    "\013\uffeb\014\uffeb\015\uffeb\016\uffeb\021\uffeb\022\uffeb\054" +
    "\uffeb\001\002\000\034\004\uffe9\005\uffe9\006\uffe9\010\uffe9" +
    "\011\uffe9\012\uffe9\013\uffe9\014\uffe9\015\uffe9\016\uffe9\021" +
    "\uffe9\022\uffe9\054\uffe9\001\002\000\024\005\uffd9\006\uffd9" +
    "\010\uffd9\012\uffd9\014\uffd9\016\uffd9\021\uffd9\022\uffd9\054" +
    "\uffd9\001\002\000\022\006\036\017\071\027\075\031\065" +
    "\050\072\051\067\052\076\054\045\001\002\000\004\026" +
    "\140\001\002\000\024\005\uffe1\006\uffe1\010\uffe1\012\uffe1" +
    "\014\uffe1\016\uffe1\021\uffe1\022\uffe1\054\uffe1\001\002\000" +
    "\004\053\142\001\002\000\006\020\144\025\143\001\002" +
    "\000\024\006\036\017\071\027\075\031\065\050\072\051" +
    "\067\052\076\053\146\054\045\001\002\000\012\020\uffd5" +
    "\024\uffd5\025\uffd5\026\uffd5\001\002\000\006\020\uffd1\025" +
    "\uffd1\001\002\000\006\020\uffd0\025\uffd0\001\002\000\006" +
    "\020\uffd3\025\uffd3\001\002\000\006\020\152\025\151\001" +
    "\002\000\024\006\036\017\071\027\075\031\065\050\072" +
    "\051\067\052\076\053\146\054\045\001\002\000\012\020" +
    "\uffd4\024\uffd4\025\uffd4\026\uffd4\001\002\000\006\020\uffd2" +
    "\025\uffd2\001\002\000\006\020\uffee\025\uffee\001\002\000" +
    "\012\004\ufff3\013\ufff3\015\ufff3\022\ufff3\001\002\000\006" +
    "\020\uffed\025\uffed\001\002\000\012\004\012\013\011\015" +
    "\013\022\162\001\002\000\004\002\uffff\001\002\000\012" +
    "\004\ufffc\013\ufffc\015\ufffc\022\ufffc\001\002\000\004\002" +
    "\ufffd\001\002\000\004\017\164\001\002\000\010\004\012" +
    "\013\011\020\165\001\002\000\004\021\035\001\002\000" +
    "\006\020\167\025\032\001\002\000\004\021\035\001\002" +
    "\000\012\004\ufff0\013\ufff0\015\ufff0\022\ufff0\001\002\000" +
    "\012\004\ufff2\013\ufff2\015\ufff2\022\ufff2\001\002\000\006" +
    "\025\ufff8\026\ufff8\001\002\000\012\017\025\023\201\025" +
    "\ufff7\026\ufff7\001\002\000\006\025\175\026\176\001\002" +
    "\000\004\054\200\001\002\000\012\004\ufffa\013\ufffa\015" +
    "\ufffa\022\ufffa\001\002\000\006\025\ufff9\026\ufff9\001\002" +
    "\000\010\023\201\025\ufff7\026\ufff7\001\002\000\004\050" +
    "\202\001\002\000\004\024\203\001\002\000\006\025\ufff6" +
    "\026\ufff6\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\004\013\005\016" +
    "\010\017\011\015\021\007\001\001\000\006\006\173\007" +
    "\171\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\005\160\010\156\011\015\021\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\022\021\020\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\012\030\013\027\021\025\001\001\000\002\001\001\000" +
    "\004\020\154\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\013\153\021\025\001\001\000\004\020\033\001" +
    "\001\000\002\001\001\000\020\014\040\016\042\017\052" +
    "\020\050\021\046\022\051\023\036\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\016\131" +
    "\017\052\020\050\022\051\023\036\001\001\000\002\001" +
    "\001\000\012\017\123\020\050\022\051\023\036\001\001" +
    "\000\012\022\073\023\072\025\121\030\067\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\022\073" +
    "\023\072\025\065\030\067\001\001\000\012\022\073\023" +
    "\072\025\105\030\067\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\022\073\023\072\025" +
    "\077\030\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\022\073\023\072\025\076\030" +
    "\067\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\102\001\001\000" +
    "\002\001\001\000\004\020\104\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\022\073\023\072\024\114\025" +
    "\113\030\067\001\001\000\012\022\073\023\072\025\110" +
    "\030\067\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\022\073\023\072\025\117\030\067\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\022\073\023\072\025\126\030\067\001\001\000\002" +
    "\001\001\000\004\020\130\001\001\000\002\001\001\000" +
    "\012\017\123\020\050\022\051\023\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\022" +
    "\073\023\072\025\136\030\067\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\022\073\023\072\025\144\026\147\027\146\030\067" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\022\073" +
    "\023\072\025\144\027\152\030\067\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\022\021\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\012\165\013\027\021\025\001\001\000" +
    "\004\020\170\001\001\000\002\001\001\000\004\020\167" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\176" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$DecafParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$DecafParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$DecafParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$DecafParser$actions {
  private final DecafParser parser;

  /** Constructor */
  CUP$DecafParser$actions(DecafParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$DecafParser$do_action(
    int                        CUP$DecafParser$act_num,
    java_cup.runtime.lr_parser CUP$DecafParser$parser,
    java.util.Stack            CUP$DecafParser$stack,
    int                        CUP$DecafParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$DecafParser$result;

      /* select the action based on the action number */
      switch (CUP$DecafParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Literal ::= CHAR_LITERAL 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(22/*Literal*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Literal ::= BOOLEAN_LITERAL 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(22/*Literal*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Literal ::= INT_LITERAL 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(22/*Literal*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Expr ::= LEFT_PARENTHESIS Expr RIGHT_PARENTHESIS 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Expr ::= NOT Expr 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Expr ::= MINUS Expr 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Expr ::= Literal 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Expr ::= MethodCall 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Expr ::= Location 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(19/*Expr*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Exprs ::= Exprs COMMA Expr 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(18/*Exprs*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Exprs ::= Expr 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(18/*Exprs*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Location ::= IDENTIFIER LEFT_BRACKET Expr RIGHT_BRACKET 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(17/*Location*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Location ::= IDENTIFIER 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(17/*Location*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // CalloutArg ::= STRING_LITERAL 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(21/*CalloutArg*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // CalloutArg ::= Expr 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(21/*CalloutArg*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // CalloutArgs ::= CalloutArgs COMMA CalloutArg 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(20/*CalloutArgs*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // CalloutArgs ::= CalloutArg 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(20/*CalloutArgs*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // MethodCall ::= CALLOUT LEFT_PARENTHESIS STRING_LITERAL COMMA CalloutArgs RIGHT_PARENTHESIS 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(16/*MethodCall*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // MethodCall ::= CALLOUT LEFT_PARENTHESIS STRING_LITERAL RIGHT_PARENTHESIS 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(16/*MethodCall*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // MethodCall ::= IDENTIFIER LEFT_PARENTHESIS Exprs RIGHT_PARENTHESIS 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(16/*MethodCall*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // MethodCall ::= IDENTIFIER LEFT_PARENTHESIS RIGHT_PARENTHESIS 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(16/*MethodCall*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Statement ::= Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Statement ::= CONTINUE SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Statement ::= BREAK SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Statement ::= RETURN Expr SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Statement ::= RETURN SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Statement ::= WHILE LEFT_PARENTHESIS Expr RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Statement ::= IF LEFT_PARENTHESIS Expr RIGHT_PARENTHESIS Block ELSE Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Statement ::= IF LEFT_PARENTHESIS Expr RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Statement ::= MethodCall SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Statement ::= Location EQUAL Expr SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(13/*Statement*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Statements ::= Statements Statement 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(12/*Statements*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Statements ::= Statement 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(12/*Statements*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Type ::= BOOLEAN 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(15/*Type*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(15/*Type*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // VariableDeclaration ::= VariableDeclaration COMMA IDENTIFIER 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(11/*VariableDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // VariableDeclaration ::= IDENTIFIER 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(11/*VariableDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // VariableDeclarations ::= Type VariableDeclaration SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(10/*VariableDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Block ::= LEFT_BRACE VariableDeclarations Statements RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(14/*Block*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Block ::= LEFT_BRACE Statements RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(14/*Block*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Block ::= LEFT_BRACE VariableDeclarations RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(14/*Block*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Block ::= LEFT_BRACE RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(14/*Block*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ParameterDeclaration ::= Type IDENTIFIER 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(9/*ParameterDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ParameterDeclarations ::= ParameterDeclarations COMMA ParameterDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(8/*ParameterDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ParameterDeclarations ::= ParameterDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(8/*ParameterDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // MethodDeclaration ::= VOID IDENTIFIER LEFT_PARENTHESIS ParameterDeclarations RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(7/*MethodDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // MethodDeclaration ::= Type IDENTIFIER LEFT_PARENTHESIS ParameterDeclarations RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(7/*MethodDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // MethodDeclaration ::= VOID IDENTIFIER LEFT_PARENTHESIS RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(7/*MethodDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // MethodDeclaration ::= Type IDENTIFIER LEFT_PARENTHESIS RIGHT_PARENTHESIS Block 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(7/*MethodDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // MethodDeclarations ::= MethodDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(6/*MethodDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // MethodDeclarations ::= MethodDeclarations MethodDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(6/*MethodDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Field ::= IDENTIFIER LEFT_BRACKET INT_LITERAL RIGHT_BRACKET 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(5/*Field*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Field ::= IDENTIFIER 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(5/*Field*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Fields ::= Field 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(4/*Fields*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Fields ::= Fields COMMA Field 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(4/*Fields*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // FieldDeclaration ::= Type Fields SEMI_COLON 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(3/*FieldDeclaration*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // FieldDeclarations ::= FieldDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(2/*FieldDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // FieldDeclarations ::= FieldDeclarations FieldDeclaration 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(2/*FieldDeclarations*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= CLASS IDENTIFIER LEFT_BRACE FieldDeclarations MethodDeclarations RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= CLASS IDENTIFIER LEFT_BRACE MethodDeclarations RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= CLASS IDENTIFIER LEFT_BRACE FieldDeclarations RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).value;
		RESULT = start_val;
              CUP$DecafParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$DecafParser$parser.done_parsing();
          return CUP$DecafParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= CLASS IDENTIFIER LEFT_BRACE RIGHT_BRACE 
            {
              Object RESULT = null;

              CUP$DecafParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$DecafParser$stack.elementAt(CUP$DecafParser$top-0)).right, RESULT);
            }
          return CUP$DecafParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

