
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 04 22:29:57 CEST 2010
//----------------------------------------------------

package scomp;

/** CUP generated class containing symbol constants. */
public class DecafParserSymbols {
  /* terminals */
  public static final int WHILE = 14;
  public static final int INT = 10;
  public static final int TRUE = 12;
  public static final int BOOLEAN = 2;
  public static final int VOID = 13;
  public static final int EOF = 0;
  public static final int IF = 9;
  public static final int FALSE = 8;
  public static final int ELSE = 7;
  public static final int error = 1;
  public static final int CALLOUT = 4;
  public static final int RETURN = 11;
  public static final int CONTINUE = 6;
  public static final int CLASS = 5;
  public static final int BREAK = 3;
}

