
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 04 23:37:53 CEST 2010
//----------------------------------------------------

package scomp;

/** CUP generated class containing symbol constants. */
public class DecafParserSymbols {
  /* terminals */
  public static final int CALLOUT = 4;
  public static final int CONTINUE = 6;
  public static final int CLASS = 5;
  public static final int ELSE = 7;
  public static final int LEFT_BRACE = 15;
  public static final int INT = 9;
  public static final int WHILE = 12;
  public static final int BOOLEAN_LITERAL = 20;
  public static final int IDENTIFIER = 23;
  public static final int RETURN = 10;
  public static final int IF = 8;
  public static final int OPERATOR = 24;
  public static final int STRING_LITERAL = 22;
  public static final int INT_LITERAL = 19;
  public static final int BOOLEAN = 2;
  public static final int LEFT_PARENTHESIS = 13;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int EOF = 0;
  public static final int BREAK = 3;
  public static final int CHAR_LITERAL = 21;
  public static final int LEFT_BRACKET = 17;
  public static final int error = 1;
  public static final int RIGHT_BRACE = 16;
  public static final int VOID = 11;
  public static final int RIGHT_BRACKET = 18;
}

