
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 03 23:07:41 CEST 2010
//----------------------------------------------------

package scomp;

/** CUP generated class containing symbol constants. */
public class DecafParserSymbols {
  /* terminals */
  public static final int error = 1;
  public static final int KEYWORD = 2;
  public static final int EOF = 0;
}

