
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 08 01:24:56 CEST 2010
//----------------------------------------------------

package scomp;

/** CUP generated class containing symbol constants. */
public class DecafParserSymbols {
  /* terminals */
  public static final int STRING_LITERAL = 40;
  public static final int RIGHT_BRACKET = 18;
  public static final int GREATER_OR_EQUAL = 32;
  public static final int CHAR_LITERAL = 39;
  public static final int NOT_EQUAL = 34;
  public static final int ARITHMETIC_SHIFT_LEFT = 26;
  public static final int GREATER = 30;
  public static final int CONTINUE = 6;
  public static final int INT = 9;
  public static final int MINUS = 23;
  public static final int LESSER_OR_EQUAL = 31;
  public static final int BOOLEAN_LITERAL = 38;
  public static final int AND = 35;
  public static final int NOT = 21;
  public static final int CALLOUT = 4;
  public static final int OR = 36;
  public static final int COMMA = 19;
  public static final int LEFT_BRACE = 15;
  public static final int CLASS = 5;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int LESSER = 29;
  public static final int PLUS = 22;
  public static final int IF = 8;
  public static final int BITWISE_ROTATE_RIGHT = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 10;
  public static final int EQUAL = 33;
  public static final int error = 1;
  public static final int MODULO = 25;
  public static final int SEMI_COLON = 20;
  public static final int RIGHT_BRACE = 16;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int TIMES = 24;
  public static final int ELSE = 7;
  public static final int WHILE = 12;
  public static final int ARITHMETIC_SHIFT_RIGHT = 27;
  public static final int LEFT_BRACKET = 17;
  public static final int LEFT_PARENTHESIS = 13;
  public static final int INT_LITERAL = 37;
  public static final int IDENTIFIER = 41;
}

