
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 03 18:58:06 CEST 2010
//----------------------------------------------------

package java_cup.demos.listparser;

/** CUP generated class containing symbol constants. */
public class ListParserSymbols {
  /* terminals */
  public static final int LEFT_PARENTHESIS = 2;
  public static final int error = 1;
  public static final int IDENTIFIER = 4;
  public static final int RIGHT_PARENTHESIS = 3;
  public static final int EOF = 0;
}

